export const GET_COLLECTIONS_REQUEST = "GET_COLLECTIONS_REQUEST";
export const GET_COLLECTIONS_SUCCESS = "GET_COLLECTIONS_SUCCESS";
export const GET_COLLECTIONS_FAILED = "GET_COLLECTIONS_FAILED";

export const GET_BOOKS_REQUEST = "GET_BOOKS_REQUEST";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILED = "GET_BOOKS_FAILED";

export const ADD_NEW_COLLECTION_REQUEST = "ADD_NEW_COLLECTION_REQUEST";
export const ADD_NEW_COLLECTION_SUCCESS = "ADD_NEW_COLLECTION_SUCCESS";
export const ADD_NEW_COLLECTION_FAILED = "ADD_NEW_COLLECTION_FAILED";

export const EDIT_COLLECTION_REQUEST = "EDIT_COLLECTION_REQUEST";
export const EDIT_COLLECTION_SUCCESS = "EDIT_COLLECTION_SUCCESS";
export const EDIT_COLLECTION_FAILED = "EDIT_COLLECTION_FAILED";

export const DELETE_COLLECTION_REQUEST = "DELETE_COLLECTION_REQUEST";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_FAILED = "DELETE_COLLECTION_FAILED";

export const ADD_NEW_BOOK_TO_COLLECTION_REQUEST = "ADD_NEW_BOOK_TO_COLLECTION_REQUEST";
export const ADD_NEW_BOOK_TO_COLLECTION_SUCCESS = "ADD_NEW_BOOK_TO_COLLECTION_SUCCESS";
export const ADD_NEW_BOOK_TO_COLLECTION_FAILED = "ADD_NEW_BOOK_TO_COLLECTION_FAILED";

export const ADD_NEW_BOOK_REQUEST = "ADD_NEW_BOOK_REQUEST";
export const ADD_NEW_BOOK_SUCCESS = "ADD_NEW_BOOK_SUCCESS";
export const ADD_NEW_BOOK_FAILED = "ADD_NEW_BOOK_FAILED";

export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAILED = "DELETE_BOOK_FAILED";

export const DELETE_BOOK_FROM_COLLECTION_REQUEST = "DELETE_BOOK_FROM_COLLECTION_REQUEST";
export const DELETE_BOOK_FROM_COLLECTION_SUCCESS = "DELETE_BOOK_FROM_COLLECTION_SUCCESS";
export const DELETE_BOOK_FROM_COLLECTION_FAILED = "DELETE_BOOK_FROM_COLLECTION_FAILED";